export const skills = [
  {
    name: "HTML",
    level: 100,
    tags: ["Semantic", "Accessibility", "SEO", "Forms"],
    image: "/images/skills/html.svg",
  },
  {
    name: "CSS",
    level: 88,
    tags: ["Responsive", "Tailwind", "Bootstrap"],
    image: "/images/skills/css.svg",
  },
  {
    name: "JavaScript",
    level: 90,
    tags: ["ES6+", "Async"],
    image: "/images/skills/javascript.svg",
  },
  {
    name: "TypeScript",
    level: 80,
    tags: ["Type Safety", "OOP"],
    image: "/images/skills/typescript.svg",
  },
  {
    name: "C# (.NET)",
    level: 94,
    tags: ["MVC", "LINQ", "Entity Framework", "SignalR"],
    image: "/images/skills/csharp.svg",
  },
  {
    name: "Blazor",
    level: 60,
    tags: ["WebAssembly", "MAUI (Blazor Hybrid)", "Radzen"],
    image: "/images/skills/blazor.svg",
  },
  {
    name: "NodeJS",
    level: 72,
    tags: ["Express", "REST API"],
    image: "/images/skills/nodejs.svg",
  },
  {
    name: "React",
    level: 90,
    tags: ["Hooks", "JSX", "Redux", "SPA"],
    image: "/images/skills/react.svg",
  },
  {
    name: "Next.js",
    level: 60,
    tags: ["SSR", "SSG", "API Routes", "App Router"],
    image: "/images/skills/next-js.svg",
  },
  {
    name: "React Native",
    level: 70,
    tags: ["Mobile", "Expo", "Navigation", "Hooks"],
    image: "/images/skills/react-native.svg",
  },
  {
    name: "Electron",
    level: 74,
    tags: ["Desktop", "IPC", "Main/Renderer"],
    image: "/images/skills/electron.svg",
  },
  {
    name: "SQL",
    level: 88,
    tags: ["MySQL", "MS SQL Server", "SQLite", "PostgreSQL"],
    image: "/images/skills/sql.svg",
  },
  {
    name: "MongoDB",
    level: 84,
    tags: ["NoSQL", "Aggregation", "Indexes", "Mongoose"],
    image: "/images/skills/mongodb.svg",
  },
  {
    name: "Firebase",
    level: 80,
    tags: ["Firestore", "Auth", "Realtime DB", "Hosting"],
    image: "/images/skills/firebase.svg",
  },
  {
    name: "Azure",
    level: 80,
    tags: ["DevOps", "Pipelines", "Functions", "App Service"],
    image: "/images/skills/azure.svg",
  },
  {
    name: "Git",
    level: 90,
    tags: ["Version Control", "Branching", "Merging"],
    image: "/images/skills/git.svg",
  },
  {
    name: "Three.js",
    level: 15,
    tags: ["WebGL", "3D Models"],
    image: "/images/skills/threejs.svg",
  },
  {
    name: "Figma",
    level: 50,
    tags: ["UI/UX Design", "Site Building"],
    image: "/images/skills/figma.svg",
  },
  {
    name: "Docker",
    level: 60,
    tags: ["Containers", "Docker Compose", "Images"],
    image: "/images/skills/docker.svg",
  },
  {
    name: "Arduino",
    level: 50,
    tags: ["Microcontroller", "Sensors"],
    image: "/images/skills/arduino.svg",
  },
  {
    name: "Raspberry Pi",
    level: 50,
    tags: ["IoT", "Linux", "GPIO"],
    image: "/images/skills/raspberry-pi.svg",
  },
];