name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Raspberry Pi
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.RASPBERRY_PI_HOST }}
          username: ${{ secrets.RASPBERRY_PI_USERNAME }}
          key: ${{ secrets.RASPBERRY_PI_SSH_KEY }}
          source: "dist/."
          target: "/var/www/portfolio"
          strip_components: 0
          overwrite: true
          rm: true 